language: node_js
cache: yarn
notifications:
  email: true
node_js:
  - '10'
  - '9'
  - '8'
install:
  - yarn install
  - yarn global add codecov
script:
  - yarn lint
  - yarn test
  - codecov
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
